[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["greetservicecham"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "greetservicecham"
  org = "chameerawso2"
  version = "3.1.1"

